package com.kang.utils;

public enum MsgCode {
    REGISTER_USERNAME_EXISTED, REGISTER_SUCCESS,
    LOGIN_UNMATCHED, LOGIN_SUCCESS, LOGIN_NO_ACCOUNT,
    TOKEN_WRONG, TOKEN_EXPIRED_OR_NOT_EXISTS, TOKEN_NOT_GENERATE,
    OTHER_FAILED, OTHER_SUCCESS,
    EDIT_PASSWORD_THE_SAME, EDIT_PERMISSION,
    CREATE_ACTIVITY_FAILED, CREATE_ACTIVITY_SUCCESS,
    EDIT_ACTIVITY_FAILED, EDIT_ACTIVITY_SUCCESS,
    PARTICIPATION_DUPLICATION,
    SCRATCH_FORBIDDEN_DUE_TO_NO_PARTICIPATION, SCRATCH_LIMITED,
    ASSISTANCE_LIMITED,
    PERMISSION_DENY,
}
